resources:
  - name: dwpdigital-docker-tflint
    type: registry-image-resource
    source:
      repository: dwpdigital/docker-tflint
    check_every: 5m

  - name: ecr-dwpdigital-docker-tflint-dev
    .: (( inject meta.resources.ecr-resource ))
    source:
      repository: "docker-tflint"

  - name: ecr-dwpdigital-docker-tflint
    .: (( inject meta.resources.ecr-resource ))
    source:
      repository: "docker-tflint"
      aws_role_arn: arn:aws:iam::((dataworks.aws_management_acc)):role/ci

jobs:
  - name: mirror-dwpdigital-docker-tflint-dev
    serial_groups: [docker-tflint]
    plan:
      - get: dwpdigital-docker-tflint
        trigger: true
        params:
          format: oci
        attempts: 3
      - put: ecr-dwpdigital-docker-tflint-dev
        params:
          image: "dwpdigital-docker-tflint/image.tar"
        attempts: 3

  - name: mirror-dwpdigital-docker-tflint
    serial_groups: [docker-tflint]
    plan:
      - get: dwpdigital-docker-tflint
        trigger: true
        params:
          format: oci
        attempts: 3
      - put: ecr-dwpdigital-docker-tflint
        params:
          image: "dwpdigital-docker-tflint/image.tar"
        attempts: 3
