jobs:
  - name: docker-tflint-pr
    plan:
      - get: docker-tflint-pr
        trigger: true
        version: every
      - put: docker-tflint-pr
        params:
          path: docker-tflint-pr
          status: pending
        input_mapping:
          docker-tflint: docker-tflint-pr
      - .: (( inject meta.plan.terraform-bootstrap ))
        input_mapping:
          docker-tflint: docker-tflint-pr
      - .: (( inject meta.plan.terraform-plan ))
        input_mapping:
          docker-tflint: docker-tflint-pr
        params:
          TF_WORKSPACE: "management-dev"
          DETAILED_EXITCODE: ""
        on_failure:
          put: docker-tflint-pr
          params:
            path: docker-tflint-pr
            status: failure
        on_success:
          put: docker-tflint-pr
          params:
            path: docker-tflint-pr
            status: success
